load("@bom_join_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "join",
    srcs = [
        "join.py",
    ],
    main = "join.py",
    python_version = "PY3",
)
