load("//bazel:defs.bzl", "kicad_hardware")

kicad_hardware(
    name = "thermistors",
    schematic_files = [
        "thermistors.kicad_sch",
        "17-thermistor-7-probe.kicad_sch",
        "20-thermistor-group-4-probes.kicad_sch",
        "24-thermistor-group.kicad_sch",
    ],
)