py_binary(
    name = "kernel_init",
    srcs = ["hardware_setup.py"],
    main = "hardware_setup.py",
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)
