#!/bin/bash

#use this if you're running the script yourself
#dir="$(pwd)/can_logs/"

#cron script run
dir="//home/oemdashboard/can_logs/"

# find the current maximum value
current_max=$( 
    find "$dir" -name mk6_\*.log -print0 \
    | sort -z -V \
    | tail -z -n 1
)
if [[ ! $current_max =~ _([0-9]+)\.log ]]; then
    counter="0"
else 
    # increment it
    counter=$(( 1 + ${BASH_REMATCH[1]} ))
fi

echo ${dir}

touch ${dir}mk6_${counter}.log
/usr/bin/python -m can.logger -f ${dir}mk6_${counter}.log -c can0 -b 500000 -i socketcan

