load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "crc32",
    srcs = [
        "crc32.c",
    ],
    hdrs = [
        "crc32.h",
    ],
    visibility = ["//visibility:public"],
)
