load("@rules_python//python:defs.bzl", "py_binary")
load("@symbol_libraries_deps//:requirements.bzl", "requirement")

py_binary(
    name = "libraries",
    srcs = [
        "libraries.py",
    ],
    python_version = "PY3",
    main = "libraries.py",
)
