load("@rules_python//python:defs.bzl", "py_binary")
load("@symbol_library_converter_deps//:requirements.bzl", "requirement")

py_binary(
    name = "convert",
    srcs = [
        "convert.py",
    ],
    main = "convert.py",
    python_version = "PY3",
)
