load("//bazel:defs.bzl", "kicad_hardware")

kicad_hardware(
    name = "service_section_controller",
    schematic_files = ["service_section_controller.sch"] + glob(
        ["*.sch"],
        ["service_section_controller.sch"],
    ),
)
