load("//bazel:defs.bzl", "kicad_hardware")

kicad_hardware(
    name = "tsal-ail",
    schematic_files = ["tsal-ail.kicad_sch"] + glob(
        ["*.kicad_sch"],
        ["tsal-ail.kicad_sch"],
    ),
)
