load("//bazel:defs.bzl", "kicad_hardware")

kicad_hardware(
    name = "bms_core",
    schematic_files = [
        "bms_core.kicad_sch",
        "bspd_current_sense.kicad_sch",
        "isospi-interface.kicad_sch",
        "m_2_connector.kicad_sch",
    ],
)
