load("//bazel:defs.bzl", "kicad_hardware")

kicad_hardware(
    name = "precharge_discharge",
    schematic_files = [
        "precharge_discharge.kicad_sch",
        "thermistor.kicad_sch",
    ],
)
