load("//bazel:defs.bzl", "kicad_hardware")

kicad_hardware(
    name = "sensing_controller", 
    schematic_files = ["sensing_controller.sch", "connectors.sch", "micros.sch", "power.sch", "suspension_strain_individual.sch", "suspension_strain.sch", "suspension_travel.sch", "tire_temp.sch", "wheel_speed.sch"],
)
