load("//bazel:defs.bzl", "kicad_hardware")

kicad_hardware(
    name = "sensing_controller",
    schematic_files = [
        "sensing_controller.kicad_sch",
        "connectors.kicad_sch",
        "micros.kicad_sch",
        "power.kicad_sch",
        "suspension_strain_individual.kicad_sch",
        "suspension_strain.kicad_sch",
        "suspension_travel.kicad_sch",
        "tire_temp.kicad_sch",
        "wheel_speed.kicad_sch",
    ],
)
