load("//bazel:defs.bzl", "kicad_hardware")


kicad_hardware(
    name = "cooling_sense",
    schematic_files = ["cooling_sense.sch"] + glob(
        ["*.sch"],
        ["cooling_sense.sch"],
    ),
)
