/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 35.5.0 Mon May 10 14:54:37 2021.
 */

#include <string.h>

#include "shutdown.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int shutdown_brakelight_bspd_shutdown_pack(
    uint8_t *dst_p,
    const struct shutdown_brakelight_bspd_shutdown_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->error_code, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->brake_analog_voltage_msb, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_analog_voltage_lsb, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_gate, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->bspdsense, 0u, 0xffu);

    return (5);
}

int shutdown_brakelight_bspd_shutdown_unpack(
    struct shutdown_brakelight_bspd_shutdown_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->error_code = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->brake_analog_voltage_msb = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->brake_analog_voltage_lsb = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->brake_gate = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->bspdsense = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

bool shutdown_brakelight_bspd_shutdown_error_code_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool shutdown_brakelight_bspd_shutdown_brake_analog_voltage_msb_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool shutdown_brakelight_bspd_shutdown_brake_analog_voltage_lsb_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool shutdown_brakelight_bspd_shutdown_brake_gate_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool shutdown_brakelight_bspd_shutdown_bspdsense_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
