; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_g431kb]
platform = ststm32
board = nucleo_g431kb
framework = stm32cube

# Add the include directory to the build flags
build_flags = -I include

# Ensure all source files from the src directory are compiled
build_src_filter = +<*> -<.git/> -<.svn/>

# --- Uploader and Debugger Configuration ---
# You will need an ST-Link programmer/debugger to flash your custom board.
upload_protocol = stlink
debug_tool = stlink