load("//bazel/tools:defs.bzl", "dbc_gen")

# Generates DBC
dbc_gen(
    name = "mkvii.dbc",
    srcs = [
        #"//vehicle/common/emeter:emeter.dbc",
        #"//vehicle/common/gmeter:gmeter.dbc",
        #"//vehicle/common/lpms-cu2:lpms-cu2.dbc",
        #"//vehicle/common/motor_controller:motor_controller.dbc",
        #"//vehicle/mkvii/software/air_control:air.yml",
        #"//vehicle/mkvii/software/bms:bms.yml",
        "//vehicle/mkvii/software/bspd:bspd.yml",
        # "//vehicle/mkvii/software/charging:charger.yml",
        #"//vehicle/mkvii/software/dashboard:dashboard.yml",
        #"//vehicle/mkvii/software/throttle:throttle.yml",
    ],
)
