load("//bazel/tools:defs.bzl", "dbc_gen")

# Generates DBC
dbc_gen(
    name = "mkvi.dbc",
    srcs = [
        "//vehicle/common/emeter:emeter.dbc",
        "//vehicle/common/motor_controller:motor_controller.dbc",
    ],
)
