load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "flash",
    srcs = [
        "flash.c",
    ],
    hdrs = [
        "flash.h",
    ],
    visibility = ["//visibility:public"],
)
