load("//bazel:defs.bzl", "kicad_hardware")

kicad_hardware(
    name = "internal_interface",
    # project_file = "internal_interface.pro",
    # schematic_files = [
    #     "internal_interface.sch",
    # ],
    # pcb_file = "internal_interface.kicad_pcb",
    # lib_cache = "internal_interface-cache.lib",
)
