M48
; DRILL file {KiCad 7.0.8} date 2024 September 16, Monday 14:38:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-16T14:38:22-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
%
G90
G05
T1
X241.4Y-68.85
X241.4Y-78.0
X241.4Y-114.75
X241.4Y-137.9
T0
M30
